### PR TITLE
fix(container): remove log_driver's default value and make log_driver `computed`

### LINKED ISSUE #269: log_driver defaults to json-file instead of letting system decide
Because log_driver is defaulted, it ignores what the system's default is. So, as an example, I've got my docker daemon setup to send longs to journald. But nothing logs out because the provider is hard set to use json-file. 

The idea that I'd have to hard set on every container what logging mechanism to use seems.. not great. Especially since this TF may be applied against different machines with different logging setups. 

### Affected Resource(s)

* `docker_container`

### Terraform Configuration Files
```hcl
resource "docker_container" "nginx" {
  name = "nginx"
  image = "nginx:latest"
}
```

/etc/docker/daemon.json
```json
{
  "log-driver": "journald"
}
```

### Debug Output

```
  + resource "docker_container" "nginx" {
      + attach           = false
      + bridge           = (known after apply)
      + command          = (known after apply)
      + container_logs   = (known after apply)
      + entrypoint       = (known after apply)
      + env              = (known after apply)
      + exit_code        = (known after apply)
      + gateway          = (known after apply)
      + hostname         = (known after apply)
      + id               = (known after apply)
      + image            = "nginx:latest"
      + init             = (known after apply)
      + ip_address       = (known after apply)
      + ip_prefix_length = (known after apply)
      + ipc_mode         = (known after apply)
      + log_driver       = "json-file"
      + logs             = false
      + must_run         = true
      + name             = "nginx"
      + network_data     = (known after apply)
      + read_only        = false
      + remove_volumes   = true
      + restart          = "no"
      + rm               = false
      + security_opts    = (known after apply)
      + shm_size         = (known after apply)
      + start            = true
      + stdin_open       = false
      + tty              = false

      + healthcheck {
          + interval     = (known after apply)
          + retries      = (known after apply)
          + start_period = (known after apply)
          + test         = (known after apply)
          + timeout      = (known after apply)
        }

      + labels {
          + label = (known after apply)
          + value = (known after apply)
        }
    }
```

### Expected Behaviour

Either the `log_driver` should be empty, or set to the same as what the system is set to. 

### Actual Behaviour

The `log_driver` is set to `json-file`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Docker daemon set to use journald logging.

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #269

## BREAKING CHANGE

* docker_container.log_driver: remove the default value and set `Computed: true`

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
I ran `make website-generation`, but the document isn't updated. 🤔 

```console
$ make website-generation 
go generate
rendering website for provider "terraform-provider-docker"
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "docker"
generating missing resource content
resource "docker_image" template exists, skipping
resource "docker_network" template exists, skipping
resource "docker_service" template exists, skipping
resource "docker_volume" template exists, skipping
resource "docker_config" template exists, skipping
resource "docker_container" template exists, skipping
resource "docker_plugin" template exists, skipping
resource "docker_registry_image" template exists, skipping
resource "docker_secret" template exists, skipping
generating missing data source content
generating template for "docker_plugin"
generating template for "docker_registry_image"
generating template for "docker_image"
generating template for "docker_network"
generating missing provider content
provider "terraform-provider-docker" template exists, skipping
cleaning rendered website dir
rendering templated website to static markdown
rendering "data-sources/image.md.tmpl"
rendering "data-sources/network.md.tmpl"
rendering "data-sources/plugin.md.tmpl"
rendering "data-sources/registry_image.md.tmpl"
rendering "index.md.tmpl"
rendering "resources/config.md.tmpl"
rendering "resources/container.md.tmpl"
rendering "resources/image.md.tmpl"
rendering "resources/network.md.tmpl"
rendering "resources/plugin.md.tmpl"
rendering "resources/registry_image.md.tmpl"
rendering "resources/secret.md.tmpl"
rendering "resources/service.md.tmpl"
rendering "resources/volume.md.tmpl"
```

**Comment by suzuki-shunsuke** [comment]
Oh, I see.
This description isn't auto generated.

https://github.com/kreuzwerker/terraform-provider-docker/blob/a49f8a79166485e4e35bb03118a3ea197e32ec7c/internal/provider/resource_docker_container.go#L711

**Comment by stephenliberty** [comment]
@mavogel - any chance you can review this sooner than later? There's a couple of MR's hanging out that need some attention :)

**Comment by mavogel** [comment]
@suzuki-shunsuke  shall we release this although it's a BC and then focus on Milestone 3.0 to bring this provider in shape?

**Comment by suzuki-shunsuke** [comment]
Sure. Let's focus on Milestone 3.0.

**Review by mavogel — APPROVED** [review]

**Comment by stephenliberty** [comment]
Looks like this breaks in circumstances where the log_opts are pulled from the system as well. For example, 

```
~ log_driver        = "fluentd" -> (known after apply)
- log_opts          = {
- "fluentd-address" = "localhost:24226"
- "fluentd-async"   = "true"
  } -> null # forces replacement
```

@mavogel / @suzuki-shunsuke - is this something that can be patched today, or do I need to roll back a bunch of stuff? I would assume the fix would simply be defaulting the log_opts to computed as well.

**Comment by suzuki-shunsuke** [comment]
In this pull request, `log_opts` isn't changed.
Could you create an issue?

**Comment by stephenliberty** [comment]
Done - https://github.com/kreuzwerker/terraform-provider-docker/issues/340

Hopefully that makes sense.

**Comment by suzuki-shunsuke** [comment]
Thanks!

**Pull request merged**
