### PR TITLE
Do not start container until after attach. Do not attach if container never starts.

### PR DESCRIPTION
**Pull request by innovate-invent**
This deals with a race condition that causes an error when the container starts and exits before the provider can attach.

### CODE REVIEW

**Comment by innovate-invent** [comment]
bump

**Comment by innovate-invent** [comment]
bump

**Comment by mavogel** [comment]
are you still on this @innovate-invent ? Maybe wait with the rebase until #145 is merged to avoid too many conflicts

**Comment by innovate-invent** [comment]
Yea, looks like the refactor is going to mess this up. I'll wait.

**Comment by mavogel** [comment]
i think we're ready to continue @innovate-invent  :)

**Pull request closed without merging**
