### PR TITLE
Fix image error handling

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
Ooops opened this by mistake 😅

**Comment by prologic** [comment]
@Junkern Oh hey! 👋 I just noticed you pushed a commit ~14m ago 😅

Some context on this accidental PR (_I will probably PR it again properly a bit later_); but I'm trying to root case and figure out what #262  and some other intermitent issues we're having with the `docker_image` resource.

Basically what I've boiled it down we're masking potential errors in `searchLocalImages()`:

https://github.com/kreuzwerker/terraform-provider-docker/blob/78c42d7657cd9e1ab6216fce2c798d9b09980550/internal/provider/resource_docker_image_funcs.go#L110-L122

**Comment by prologic** [comment]
@Junkern Hey is there a way we can jump on a video call and discuss some improvements I'd like to make? 🤔

**Comment by Junkern** [comment]
@prologic unusual request, but we can do that :D I'll write you an email.

**Pull request closed without merging**
