### PR TITLE
feat: add docker logs data source

### PR DESCRIPTION
**Pull request by bukowa**
This adds new data source docker logs. This is my first code for any terraform providers so i am not sure if i missed anything. I made the logs accessible as a list of strings `logs_list_string` so it should be easy to add different log types.

### CODE REVIEW

**Comment by Junkern** [comment]
Thanks a lot for the contribution! Looks good! Could you rebase and then, if all tests pass, I'll merge.

Out of personal curiosity: How do you use this?

**Comment by bukowa** [comment]
Hey @Junkern i already don't remember how i used it :laughing: 

Master is merged but i seen 2 tests not passing before but i seen they were not passing for many merges into master, is the problem on my side ?

**Comment by Junkern** [comment]
No, the problem was not on your side.
Could you also [update the documentation](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/CONTRIBUTING.md#update-the-documentation)?

**Comment by bukowa** [comment]
Documentation updated.

**Review by Junkern — APPROVED** [review]

**Pull request merged**
