### PR TITLE
fix: rewriting tar header fields (#192)

### PR DESCRIPTION
**Pull request by dlaburthe**
Fix issue with the docker_registry_image resource as per code archive best practices from https://reproducible-builds.org/.

### CODE REVIEW

**Comment by dlaburthe** [comment]
Hello @mavogel ,
I've just managed to test my modifications in a bitbucket pipeline and it works great :)
As we are blocked by this bug, do you think we could expect a release soon ?
Maybe in the 2.11 cycle ?

**Comment by suzuki-shunsuke** [comment]
`master` branch includes some unreleased breaking change, so the next release is not v2.11.1 but v3.

**Comment by dlaburthe** [comment]
ok.
Do you have an eta for the v3 ?

**Comment by mavogel** [comment]
Hi @dlaburthe we do not have an ETA, but we're working constantly on the [v3](https://github.com/kreuzwerker/terraform-provider-docker/milestone/4). You can see the progress there. Feel free to contribute. I'll take your PR in.

Thanks for fixing this bug!

**Review by mavogel — APPROVED** [review]

**Comment by mavogel** [comment]
Update @dlaburthe : we will cut a `v2.11.1` release later, as there are really only fixes until now

**Comment by dlaburthe** [comment]
Thanks @mavogel !

**Comment by pwt** [comment]
This change introduced defect https://github.com/kreuzwerker/terraform-provider-docker/issues/293

**Pull request merged**
