### PR TITLE
Docs Fix: confusing docs for registry_image auth_config

### PR DESCRIPTION
**Pull request by dav009**
This PR is a quick attempt to clarify on a rather confusing property name. Following issue https://github.com/kreuzwerker/terraform-provider-docker/issues/189

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!

**Review by suzuki-shunsuke — CHANGES_REQUESTED** [review]
CI failed. https://github.com/kreuzwerker/terraform-provider-docker/runs/4234656985?check_suite_focus=true

> Generated website was not up-to-date. Please run 'make website-generation' locally, commit, and push again

**Comment by dav009** [comment]
@suzuki-shunsuke  got this error

```
: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/Masterminds/goutils v1.1.0
go: downloading github.com/huandu/xstrings v1.3.2
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/google/uuid v1.1.2
# math/bits
compile: version "go1.16" does not match go tool version "go1.16.3"
# internal/unsafeheader
compile: version "go1.16" does not match go tool version "go1.16.3"
# internal/race
compile: version "go1.16" does not match go tool version "go1.16.3"
# unicode/utf8
compile: version "go1.16" does not match go tool version "go1.16.3"
# runtime/internal/sys
compile: version "go1.16" does not match go tool version "go1.16.3"
# encoding
compile: version "go1.16" does not match go tool version "go1.16.3"
# unicode
compile: version "go1.16" does not match go tool version "go1.16.3"
# unicode/utf16
compile: version "go1.16" does not match go tool version "go1.16.3"
# github.com/hashicorp/terraform-exec/internal/version
compile: version "go1.16" does not match go tool version "go1.16.3"
# crypto/internal/subtle
compile: version "go1.16" does not match go tool version "go1.16.3"
# internal/nettrace
compile: version "go1.16" does not match go tool version "go1.16.3"
# container/list
compile: version "go1.16" does not match go tool version "go1.16.3"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.16" does not match go tool version "go1.16.3"
# google.golang.org/protobuf/internal/flags
compile: version "go1.16" does not match go tool version "go1.16.3"
# crypto/subtle
compile: version "go1.16" does not match go tool version "go1.16.3"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.16" does not match go tool version "go1.16.3"
# google.golang.org/grpc/serviceconfig
compile: version "go1.16" does not match go tool version "go1.16.3"
# go.opencensus.io
compile: version "go1.16" does not match go tool version "go1.16.3"
# internal/cpu
compile: version "go1.16" does not match go tool version "go1.16.3"
# sync/atomic
compile: version "go1.16" does not match go tool version "go1.16.3"
# go.opencensus.io/internal/tagencoding
compile: version "go1.16" does not match go tool version "go1.16.3"
# go.opencensus.io/trace/internal
compile: version "go1.16" does not match go tool version "go1.16.3"
# github.com/aws/aws-sdk-go/aws/client/metadata
compile: version "go1.16" does not match go tool version "go1.16.3"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.16" does not match go tool version "go1.16.3"
note: module requires Go 1.17
# runtime/internal/atomic
compile: version "go1.16" does not match go tool version "go1.16.3"
# github.com/ulikunitz/xz/internal/hash
compile: version "go1.16" does not match go tool version "go1.16.3"
# image/color
compile: version "go1.16" does not match go tool version "go1.16.3"
# runtime/cgo
compile: version "go1.16" does not match go tool version "go1.16.3"
main.go:20: running "go": exit status 2
make: *** [website-generation] Error 1
```

**Comment by suzuki-shunsuke** [comment]
Do you set the environment variable `GOROOT`?
If so, could you remove it and try again?

**Pull request closed without merging**
