### PR TITLE
fix: Update the URL of the docker hub registry

### LINKED ISSUE #229: Image not found when reading a public image from docker hub
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and docker Provider) Version

Terraform version :
```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.12.2
```

Docker for Mac version :
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

 Server Version: 20.10.6
```

### Affected Resource(s)

* `docker_registry_image`

### Terraform Configuration Files

```hcl
data "docker_registry_image" "ubuntu" {
	name = "ubuntu:latest"
}

output "sha" {
	value = data.docker_registry_image.ubuntu.sha256_digest
}
```

### Debug Output

https://gist.github.com/adam-lebon/27771eb13b0b4966b354e9a6f7d2600a

### Expected Behaviour

The request to the docker registry should succeed 

### Actual Behaviour

The provider cannot read the manifest of the requested image.

The docker hub returns a 404 not found error error. Even if it is a public image.

In the first place, I thought the issue was from the docker hub. But I can't find anything related to the docker hub.

### Steps to Reproduce

1. Create a simple configuration which use a data `docker_registry_image`
2. `terraform plan`

### Important Factoids

Nothing special :
 - Tested from different IP
 - Tested from multiple OS (Docker for Mac + Docker native on ubuntu)
 - Tested manually with curl `curl -vL https://registry.hub.docker.com/v2/library/ubuntu/manifest/latest`

### PR DESCRIPTION
**Pull request by adam-lebon**
It appears that this morning, the docker hub registry stopped serving from **registry.hub.docker.com**.

In replacement, the new registry endpoint is located at **index.docker.io** as seen in every recent configurations

This breaks the data `docker_registry_image` when used with public images from the docker hub.

This pull request updates the registry URL to its new endpoint.

Resolves #229

### CODE REVIEW

**Comment by mavogel** [comment]
Alright, thanks for pointing out! I subscribe to the mentioned issue and see how it's getting resolved

**Comment by mavogel** [comment]
From the comment https://github.com/docker/hub-feedback/issues/2113#issuecomment-866298153 I see it's `registry-1.docker.io`. Can you adapt the PR? :)

**Comment by adam-lebon** [comment]
Fixes has been made, waiting for acceptance tests to be run.

**Comment by adam-lebon** [comment]
up @mavogel 
Could you please start the acceptance tests ? I don't have enough permissions to run them.
Thank you

**Review by mavogel — APPROVED** [review]

**Pull request merged**
