### PR TITLE
[WIP] ci: fix test of website

### LINKED ISSUE #12: CI of website fails
https://github.com/kreuzwerker/terraform-provider-docker/pull/8#issuecomment-736970642

https://github.com/hashicorp/terraform-website/blob/e6439bbe509a184aa06a711e5db2c050a150690e/content/scripts/check-links.sh#L34-L47

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #12

### CODE REVIEW

**Comment by mavogel** [comment]
argh sorry I made some fixes at the same time although I delegated to you (need to get it out of my head that I'm the only maintainer ...) .feel free to pick changes from here: https://github.com/kreuzwerker/terraform-provider-docker/pull/19 . I'll close it cuz it's your turn. I can review then

**Comment by mavogel** [comment]
@suzuki-shunsuke do you need any support on that? Let's get the fix done so other branches can update and the CI is green again :)

**Comment by suzuki-shunsuke** [comment]
@mavogel Thank you for your help.
I'll deal with it in the weekend.

**Comment by suzuki-shunsuke** [comment]
I'll recreate the pull request.

**Pull request closed without merging**
